name: Build the Nexora and run benchmarks

on:
  push:
    branches: [master, feat/dom]
  pull_request:
    branches: [master, feat/dom]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Benchmarks
        run: cd benchmarks && npm install && npm run benchmarks
